package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Image;
import org.mybatis.cdi.Mapper;

@Mapper
public interface ImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.IMAGE
     *
     * @mbg.generated Sun May 01 01:47:13 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.IMAGE
     *
     * @mbg.generated Sun May 01 01:47:13 EEST 2022
     */
    int insert(Image record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.IMAGE
     *
     * @mbg.generated Sun May 01 01:47:13 EEST 2022
     */
    Image selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.IMAGE
     *
     * @mbg.generated Sun May 01 01:47:13 EEST 2022
     */
    List<Image> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.IMAGE
     *
     * @mbg.generated Sun May 01 01:47:13 EEST 2022
     */
    int updateByPrimaryKey(Image record);
}