package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Language;
import org.mybatis.cdi.Mapper;

@Mapper
public interface LanguageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LANGUAGE
     *
     * @mbg.generated Sun May 01 01:47:13 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LANGUAGE
     *
     * @mbg.generated Sun May 01 01:47:13 EEST 2022
     */
    int insert(Language record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LANGUAGE
     *
     * @mbg.generated Sun May 01 01:47:13 EEST 2022
     */
    Language selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LANGUAGE
     *
     * @mbg.generated Sun May 01 01:47:13 EEST 2022
     */
    List<Language> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LANGUAGE
     *
     * @mbg.generated Sun May 01 01:47:13 EEST 2022
     */
    int updateByPrimaryKey(Language record);
}