package lt.vu.mybatis.model;

public class Image {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.IMAGE.ID
     *
     * @mbg.generated Sun May 01 01:47:13 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.IMAGE.URL
     *
     * @mbg.generated Sun May 01 01:47:13 EEST 2022
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.IMAGE.PERSON_ID
     *
     * @mbg.generated Sun May 01 01:47:13 EEST 2022
     */
    private Integer personId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.IMAGE.ID
     *
     * @return the value of PUBLIC.IMAGE.ID
     *
     * @mbg.generated Sun May 01 01:47:13 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.IMAGE.ID
     *
     * @param id the value for PUBLIC.IMAGE.ID
     *
     * @mbg.generated Sun May 01 01:47:13 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.IMAGE.URL
     *
     * @return the value of PUBLIC.IMAGE.URL
     *
     * @mbg.generated Sun May 01 01:47:13 EEST 2022
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.IMAGE.URL
     *
     * @param url the value for PUBLIC.IMAGE.URL
     *
     * @mbg.generated Sun May 01 01:47:13 EEST 2022
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.IMAGE.PERSON_ID
     *
     * @return the value of PUBLIC.IMAGE.PERSON_ID
     *
     * @mbg.generated Sun May 01 01:47:13 EEST 2022
     */
    public Integer getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.IMAGE.PERSON_ID
     *
     * @param personId the value for PUBLIC.IMAGE.PERSON_ID
     *
     * @mbg.generated Sun May 01 01:47:13 EEST 2022
     */
    public void setPersonId(Integer personId) {
        this.personId = personId;
    }
}